### ISSUE TITLE
Renaming & Compatibility

### ISSUE THREAD

**Issue by Hube2** [senlin/ymbeseo#1]
I discussed this a bit with Piet already.

When renaming we should also keep the plugin compatible with the original for a time in order to make it easy for users to switch to this new version.

1) All postmeta and other DB value names should remain unchanged until we can build an import tool to convert them to new names.

2) All functions that would be commonly used, like `yoast_breadcrumb()`
Create a file called "depricated.php" or something similar. Rename the function and add a wrapper function in deprecated that calls the new function name.
Example:
```
function yoast_breadcrumb ($before = '', $after = '', $display = true) {
  ymbeseo_breadcrumb($before, $after, $display);
}
```

3) Hooks. these would also need to be kept. My suggestion would be to create a file named "depricated-hooks.php" or something similar. Rename the hook in the plugin as well has the function that's called and then add a filter to run the old hook name to the deprecated file that calls the new function.
Example:
```
add_filter('ymbeseo_metadesc', 'depricated_wpseo_metadesc');
function depricated_wpseo_metadesc($value) {
  return apply_filters('wpseo_metadesc', $value);
}
```

There may be some additional cases that I've missed were the old names should be kept in existence.

Then at some future date when it's safe these can remove them completely.

**Comment by jdevalk** [comment]
Although you're obviously welcome to fork Yoast SEO, you're not welcome to use our brand name. So you'll *have* to rename everything.

**Comment by blueliquiddesigns** [comment]
Anyone know what's the copyright obligations are for having a function named yoast_breadcrumbs() - or similar -in the fork?

In this particular case I would think fair use would be valid to maintain backward compatibility - similar to Maria DB and MySQL.

**Comment by blueliquiddesigns** [comment]
That should read "what are the obligations for avoiding copyright infringement..."

**Comment by Hube2** [comment]
I was reading over the GPL last night, what a boring document. I don't see anything that would suggest we have to rename anything. In fact we can start distributing it as is if we choose. That's what you sign up for when you release under GPL.

**Comment by Hube2** [comment]
That being said, we do need to leave his copyright notice, give the original author(s) credit and include some about it being based on that work.

**Comment by blueliquiddesigns** [comment]
It's because Yoast SEO is trademarked so to prevent infringment the name needs to be changes. However the code is GPL so using 'yoast' in function names or db key names should be perfectly acceptable. However as the GPL has never been tested in court there is no precedent we can refer to.

**Comment by Hube2** [comment]
I was reading today about a dust up between Yoast & WPMU a few years back, forget exactly where now. At any rate, that's why I mentioned leaving their copyright in place and giving them proper credit.

**Comment by blueliquiddesigns** [comment]
That's part and parcel of the GPL. Any fork needs to meet those requirements. I read the WPMU vs Yoast issue and it looks like they were selling a commercial product and claiming it as their own but the dev who built it derived some of the code from Yoast SEO and didnt include proper attribute/copyright.

**Comment by robneu** [comment]
Why not just revert back to the original `WordPress SEO` name? It'll make it more likely to show up in search results on .org and Google anyway. If we went that route we'd just need to figure out a safe namespace for the code and remove all other references to Yoast from the codebase/docs/etc.

**Comment by Hube2** [comment]
Saying that this eventually does get put into the WordPress repo, This information has been posted to the WordPress site. New plugins submitted cannot include "WordPress" in their names. 

New plugins can also not start with the name of another plugin that does not belong to you. You can read about this here https://make.wordpress.org/plugins/2015/10/05/guidelines-for-plugins-that-include-company-andor-product-names-in-the-plugin-name/

I get emails form most of the Make WordPress. I'm sure I got the thing about not allowing WordPress in plugin names from there as well, but I didn't look for it. I would assume that the second one actually covers this as well.

**Comment by robneu** [comment]
Hmm... Maybe `https://wordpress.org/plugins/wp-seo/` would be acceptable to .org? I think that still falls within their guidelines and according to this:

>These guidelines are specifically at the slug of the plugin (wordpress.org/plugins/this-is-your-slug). The slug is auto generated based on the name you enter when submitting your plugin. After submission, you can still alter the exact name that is displayed on your plugin’s page via the readme.txt file.

It might be acceptable to make the display name WordPress SEO once the slug has been approved. We can probably pull someone like @pippinsplugins in from the plugin review team for clarification as well.

**Comment by pippinsplugins** [comment]
`wp-seo` would be acceptable.

The display name can be anything you want as long as it does not violate trademarks or copyrights.

**Comment by robneu** [comment]
Thanks @pippinsplugins! Do you know whether or not `WordPress SEO` would violate the foundation's trademarks or copyrights? If not, is there someone to reach out to about it?

**Comment by khromov** [comment]
I can think of some creative ways to register `yoast_` functions / filters without adding them to the source code.

One way would be to have a "Compatibility" option in the plugin with a text field where the user would fill in the name of the plugin they want to be backwards compatible with. The *user* would then fill in `yoast` into the metabox and all relevant filters and functions would be dynamically created.

That being said, like @blueliquiddesigns said there is no precedent for this.

**Comment by pippinsplugins** [comment]
Yes it would. You could do "SEO for WordPress.".

**Comment by senlin** [comment]
Hi guys, thanks for all your input and sorry to reply so late. 

I'm on holiday with hardly any internet access. I will get back to all of this after Dec 14th. 

Cheers,
Piet

**Comment by QWp6t** [comment]
I say you disregard @jdevalk's empty threats. Don't rename functions or hooks, but deprecate them.

In fact, don't ever get rid of the proposed `deprecated.php`. Keep the functions defined in there, so when users go to activate the official yoast plugin, they'll get fatal errors because the functions are already defined in this plugin. That would be fantastic. :trollface:

**Comment by pippinsplugins** [comment]
@QWp6t No. We'll not allow you to do that inside of the WordPress.org. Including code that will knowingly break other plugins is a violation of WordPress.org rules.

**Comment by senlin** [comment]
I think that I want to keep the name YMBE SEO, I don't see how that conflicts with anything existing.

**Comment by robneu** [comment]
@senlin Would it still be an acronym or would the name just become YMBE SEO?

**Comment by senlin** [comment]
@robneu Well... using Yoast in the name, slug and/or display name is not allowed per the rules. 

And then we will make it very clear that the YMBE SEO plugin is a fork of Yoast SEO version 2.3.5 and further bloat removed to make it a functional and clean SEO plugin :)

**Comment by robneu** [comment]
Works for me!

**Comment by khromov** [comment]
On filter/function compatibility with Yoast, we could host a small shim plugin or snippet on GitHub with instructions for how to install it in the readme.

**Comment by senlin** [comment]
Okay, the name of the plugin has been decided then: YMBE SEO

@khromov That would work for people familiar with Github, but what about the people who are not and just want to switch from bloat to YMBE SEO?

**Comment by khromov** [comment]
We could provide clear instructions (there is a Download Zip feature on GitHub already)  so it's very simple to download and then upload it to your wordpress site, it is no more difficult than any premium plugins. The shim plugin would also likely not require any updates. 

Other than that, I suggested another alternative further up in this thread that uses a more creative approach. :) 

https://github.com/senlin/ymbeseo/issues/1#issuecomment-162234151

**Comment by senlin** [comment]
Your earlier comment is a very creative solution indeed :) 
I think that although releasing the fork will most likely cause some stirring and ripples in the community, I don't want to cause any troubles or problems as that simply is not worth it. 

We simply have gotten tired of the bloat that has been added to the original plugin over time and therefore we have forked an earlier version of the original plugin.

Although we cannot use the name, I don't see why we cannot use it as @Hube2 explains it in his [original comment](https://github.com/senlin/ymbeseo/issues/1#issue-120173292)

**Comment by senlin** [comment]
Also see the [earlier comment](https://github.com/senlin/ymbeseo/issues/1#issuecomment-162139337) of @blueliquiddesigns on this.

**Comment by khromov** [comment]
I got the feeling from @jdevalk that he doesn't approve of such a solution though, it's probably not worth taking a legal battle over something silly like that, just my 2c.

**Comment by senlin** [comment]
Of course I want to avoid that too, but just as you can use `twentyfifteen_` in function names, you should also be able to use `yoast_` in function names.

Anyone else can give input on this?
