### ISSUE TITLE
Remove Admin Pointers

### ISSUE THREAD

**Issue by robneu** [senlin/ymbeseo#10]
The admin pointers loaded in the plugin are one of the more annoying things about it. I actually have code in our customer plugin at WP Site Care that disables the pointers API entirely for all customer sites, so it's safe to say that I'm not a fan.

I don't think any of the pointers in the current plugin serve any purpose beyond marketing, so it probably should be fine to rip them out.

**Comment by senlin** [comment]
Definitely rip that stuff
