### ISSUE TITLE
Fix inconstant case for functions/actions/fitlers etc

### ISSUE THREAD

**Issue by robneu** [senlin/ymbeseo#11]
It looks like when the initial renaming was done a bulk replacement for `wpseo` was performed without checking for case sensitivity. This has created a lot of strangely named [functions](https://github.com/senlin/ymbeseo/blob/master/admin/ajax.php#L264), [action hooks](https://github.com/senlin/ymbeseo/blob/master/admin/pages/social.php#L42), [filters](https://github.com/senlin/ymbeseo/blob/1157872d124b830ceee5bbbc458bbc760c0663bf/frontend/class-googleplus.php#L62), etc.

This violates WP coding standards and will probably make things kind of confusing for anyone trying to filter or add to output in the plugin. I think the fastest way to fix it might be to revert the original rename and run it again with case-sensitive replacements.

It might be worth waiting until a finalized name for the plugin is settled on so we don't have to update the namespace again. Related to #1

**Comment by senlin** [comment]
yes that is my mistake, we might have to revert that initial commit (or start clean in another branch and merge that back into the master)

**Comment by robneu** [comment]
Pulling in a fresh copy of `2.3.5` might be a good idea. We're also missing some of the development tools that have been added to WP SEO fairly recently like Grunt, Bower, etc. I'll open a new issue to discuss the inclusion if those.

**Comment by robneu** [comment]
Okay, this is resolved in the [development](https://github.com/senlin/ymbeseo/tree/development) branch and I think we're even with master as far as feature removal and other issues are concerned. I had to pull in a fresh copy of `2.3.5` so the git history is a little odd, but I think we're good to go for now.

If you run `composer install` the plugin will activate and function normally on that branch. We still need to settle on a final plugin name and code namespace, but that's not really related to this so I'm gonna close it out for now.
