### ISSUE TITLE
Remove option to add meta keywords

### ISSUE THREAD

**Issue by senlin** [senlin/ymbeseo#13]
As this is a waste of time anyways, I would like to propose to remove this option altogether.

**Comment by robneu** [comment]
:+1:

**Comment by senlin** [comment]
@robneu Can you please have a look at https://github.com/senlin/ymbeseo/blob/development/inc/options/class-ymbeseo-taxonomy-meta.php#L285-L294?
Apart from the metakeyword it makes a reference to the breadcrumb and I don't know if I can just remove that or not? If it is safe, please go ahead.

**Comment by robneu** [comment]
I'm not entirely sure why it needs that extra condition, but that's also validating the breadcrumbs data so you can't remove it without some refactoring. You should be able to safely remove [this line](https://github.com/senlin/ymbeseo/blob/development/inc/options/class-ymbeseo-taxonomy-meta.php#L285) though.

**Comment by senlin** [comment]
Cool, thanks

**Comment by senlin** [comment]
There are now 4 files left with references to `metakey`:

* admin/class-import-aioseo.php
* admin/class-import-external.php
* admin/class-import-woothemes-seo.php
* inc/class-ymbeseo-meta.php

All are related to the import function and what happens to the import of keywords. TBH I have no idea how to deal with those. Any ideas?

**Comment by robneu** [comment]
We can probably remove `admin/class-import-aioseo.php` and `admin/class-import-woothemes-seo.php` as well as possibly `admin/class-import-external.php` because of #15 

I'll have to take a look at `inc/class-ymbeseo-meta.php` and see what's up there.

**Comment by senlin** [comment]
Cool, I'll remove those 3 files then. Will leave the other one to you :)

**Comment by robneu** [comment]
I went ahead and pulled out the two plugin importers. The external one looks like it could possibly be useful if we want to allow people to import from Joost's other old plugins. Probably should continue discussion about that over in #15

**Comment by senlin** [comment]
Thanks @robneu I guess we can close this one now then?

**Comment by robneu** [comment]
I think we probably can. I looked at `inc/class-ymbeseo-meta.php` and I don't think it actually has anything to do with the meta keywords, they just used a weird naming convention for handling post meta keys. I'm not 100% sure though, the file is a bit on the confusing side.

**Comment by senlin** [comment]
Glad I'm not alone :)

I will close this one and open a new one for that file only, so we (or someone else) can have a look later.
