### ISSUE TITLE
Remove Focus Keyword

### ISSUE THREAD

**Issue by senlin** [senlin/ymbeseo#14]
I am not entirely sure what good this does, if any. If it indeed is not very useful, I want to suggest we remove it completely.

Input welcome.

**Comment by PointandStare** [comment]
Each time I tried this it gave crazy results/ suggestions totally irrelevant to the content.
I say DUMP.

**Comment by robneu** [comment]
The actual search portion of it is fairly useless, but keeping a record of which keywords have been targeted by each piece of content so that you can avoid keyword cannibalization is pretty useful.

**Comment by senlin** [comment]
> keeping a record of which keywords have been targeted by each piece of content so that you can avoid keyword cannibalization

Hmmm, that is an idea. So then we need to remove the search portion of this feature. Who is up for it?

**Comment by chuckreynolds** [comment]
:+1:
