### ISSUE TITLE
Remove Plugin Importers

### ISSUE THREAD

**Issue by robneu** [senlin/ymbeseo#15]
There are a number of standalone plugin data importers built into WordPress SEO. As far as I can tell, these are mainly there for legacy reasons and can be handled more effectively by the [SEO Data Transporter](https://wordpress.org/plugins/seo-data-transporter/) plugin.

The only issue I can see with that is that we'd need to get @nathanrice, the author of that plugin to add this plugin to the list of supported data sets.

**Comment by senlin** [comment]
:+1:

**Comment by nathanrice** [comment]
Can do. I'll add it ASAP.

**Comment by senlin** [comment]
Great, thanks @nathanrice

**Comment by robneu** [comment]
Do you think there's any reason to continue support imports from Joost's old plugins? They still have a pretty decent number of active installs, but they've been unsupported for years so that tends to suggest people aren't moving away from them.

If we don't want to support importing any external plugins, we should be able to get rid of the `YMBESEO_Import_External` class and the code which runs it.

**Comment by senlin** [comment]
Headspace, does that still exists? ;) I'd say to get rid of it. 
Initially most users of our plugin will come from the user-base of Yoast. Perhaps later on users from other plugins want to give YMBE SEO a go, then they can use Nathan's plugin.

**Comment by robneu** [comment]
Sounds good! Once Nathan has YMBE SEO added to the transporter, they should be able to use that to migrate from Yoast as well.
