### ISSUE TITLE
Remove Settings Page Sidebar

### ISSUE THREAD

**Issue by robneu** [senlin/ymbeseo#17]
Should the sidebar and all related code be removed entirely or would you prefer to keep it there for donations or something along those lines?

**Comment by senlin** [comment]
Which sidebar are we talking about exactly? I think that with my [SO Clean Up Yoast SEO plugin](https://wordpress.org/plugins/so-clean-up-wp-seo/) I am not showing the sidebar. To my own plugins I usually add something small at the bottom of the settings page. As this plugin is going to be a work of many I think it will be nice to add an "About" page to the plugin settings or something like that, where people can go if they want to know more about the plugin. Donations can be done in kind by leaving 5 star reviews :)
