### ISSUE TITLE
Remove License System

### ISSUE THREAD

**Issue by robneu** [senlin/ymbeseo#18]
Obviously we won't be selling any premium Yoast plugins through this plugin, so I think this is probably safe to remove. :grinning:

**Comment by PointandStare** [comment]
Why not go freenium on it?

**Comment by robneu** [comment]
Who would get the money from the sales? This is a group effort, so splitting up profits could get pretty weird...

**Comment by PointandStare** [comment]
Agreed - then we're getting into the realms of 'company/ business'.
Just thinking going forward etc.

**Comment by senlin** [comment]
No premium/freemium/adds that can be removed for a fee only. This fork is to clean up all the crap that team Yoast has added to what once was a decent SEO plugin. Let's please steer clear from anything else other than donations in the form of 5 star ratings and reviews and contributions to the repo itself.
