### ISSUE TITLE
Remove the columns on Posts/Pages screens

### ISSUE THREAD

**Issue by senlin** [senlin/ymbeseo#20]
The 3 admin columns have long been a total frustration and I know that many people remove them by default. I would like to suggest to simply get rid of them entirely.

**Comment by robneu** [comment]
I agree they're terrible. I do find the single colored light to be useful though. I think at some point the defaults were changed so that only that column displays but I can't remember what version it was.

Would you be okay with keeping the single SEO score column?

**Comment by senlin** [comment]
To be honest I don't see the point of the SEO score. 

For example the score is only calculated on what has been added to the WP Editor; themes that use a lot of custom fields for content get a bad or non-existing score, which is completely irrelevant.
There are more examples of irrelevance.

I think if we decide to keep it, we should make it an option that can be turned on for people that want to see the SEO score of their content.

Could that be an idea?

**Comment by PointandStare** [comment]
I always removed these in functions.php as standard in all new builds.
