### ISSUE TITLE
Remove validation error featured image smaller than 200x200px

### ISSUE THREAD

**Issue by senlin** [senlin/ymbeseo#22]
Yoast SEO 2.1 introduced 
> a validation error when a user selects a featured image for a post that is smaller than 200x200 pixels

Let's give people back the freedom to add any image they want!

**Comment by robneu** [comment]
Looks like this was done entirely in JS, so I think 52a68ae should take care of it.

**Comment by senlin** [comment]
This indeed is fixed, closing it out
