### ISSUE TITLE
Social media integration

### ISSUE THREAD

**Issue by senlin** [senlin/ymbeseo#23]
Given the fact that all social media change their APIs and what not every 3 months orso, I think the way of the least resistance is to simply remove the lot than to trying to keep up with all these different media.

Opinions please!

**Comment by QWp6t** [comment]
Are you talking about social media metadata that gets added to the head of each page? 

This stuff?


**Google+ / Schema.org**
```html
<link rel="author" href="">
<link rel="publisher" href="">
<meta itemprop="name" content="">
<meta itemprop="description" content="">
<meta itemprop="image" content="">
```


**Search Engines**
```html
<meta name="author" content="">
<meta name="description" content="">
<link rel="canonical" href="">
```


**Twitter**
```html
<meta name="twitter:card" content="">
<meta name="twitter:site" content="">
<meta name="twitter:creator" content="">
<meta name="twitter:title" content="">
<meta name="twitter:description" content="">
<meta name="twitter:image:src" content="">
```


**Facebook / Open Graph**
```html
<meta property="fb:admins" content="">
<meta property="fb:app_id" content="">
<meta property="og:url" content="">
<meta property="og:type" content="">
<meta property="og:title" content="">
<meta property="og:image" content="">
<meta property="og:description" content="">
<meta property="og:site_name" content="">
<meta property="article:author" content="">
<meta property="article:publisher" content="">
```

I think that's probably a good thing to keep.

**Comment by robneu** [comment]
I'd also prefer to keep this stuff. There aren't really good alternative plugins available for including the correct OG tags and it's pretty important for social integration.

None of the stuff in the plugin actually interfaces with any social site APIs so It shouldn't need to be updated too frequently.

**Comment by senlin** [comment]
If you think it is all manageable then we keep it, I was just afraid of ever changing methods it is hard to keep up.

**Comment by daltonrooney** [comment]
I'm strongly in favor of keeping this, if it's not too much to manage!

**Comment by senlin** [comment]
okay, let's keep this then.
