### ISSUE TITLE
What are we going to do with robots.txt generation?

### ISSUE THREAD

**Issue by senlin** [senlin/ymbeseo#25]
There are and have been many issues around this topic. Team Yoast has written several articles about it and people are still confused.

Do we generate a one-size-fits-all file or do we remove it or do we offer a suggestion/option or something else?

Input please

**Comment by robneu** [comment]
I think it should probably be removed along with the .htaccess file editor. The .htaccess one can lock people out of their site, plus apache is getting less and less common on newer WP sites as people migrate to nginx.

**Comment by senlin** [comment]
Okay let's remove both then.

**Comment by Hube2** [comment]
:) Just in case you want more up votes. The .htaccess editor was one of the worst features to add in the first place. One syntax error and you bring the site down. Always made me wonder what they were thinking when they added it. And the main reason I need to disable file modification on sites for those admins that like to poke there fingers where they don't belong.

The robots.txt field is automatically generated by WP and can be easily modified with filters. I would only add two things.
1st) The default sitemap generated by WP is:
```
User-agent: *
Disallow: /wp-admin/
```
And it should be something like:
```
User-agent: *
Allow: /wp-admin/admin-ajax.php
Disallow: /wp-admin/
```
The reason being that sites using AJAX will can fail to validate as mobile friendly using the first one. I think that this might be considered SEO. Not sure if is should be part of the plugin though.

2nd) Sitemap URL
If the sitemaps of this plugin will be kept, or it is made into an add on or whatever, then enabling sitemaps should automatically add the correct sitemap link to the robots.txt file.
```
User-agent: *
Allow: /wp-admin/admin-ajax.php
Disallow: /wp-admin/

Sitemap: http://www.mysite.com/sitemap_index.xml
```

**Comment by senlin** [comment]
@Hube2 Thanks for the up vote on removing the .htaccess editor :)

I didn't know about the robots.txt, so your vote is to keep it then?

**Comment by Hube2** [comment]
Are we talking the robots.txt editor? I have no use for the editor to be honest, I have not seen an instance were I needed to block bots from crawling something. Usually if we don't what bots to find something we don't want anyone to find it and we use a 301. Most reputable crawlers don't crawl what they not supposed to anyway and putting stuff in the robots.txt file only tells robots that don't follow the rules where to look.

What I'm talking about is a simple filter on a standard WP hook, something like this one that I use.

```
  add_filter('robots_txt', array($this, 'robots_txt_update'), 10, 2);
  function robots_txt_update($output, $public) {
    if (!$public) {
      return $output;
    }
    
    // allow bots to crawl admin ajax
    $find = 'Disallow: /wp-admin/';
    $replace = 'Allow: /wp-admin/admin-ajax.php'."\r\n".$find;
    $output = str_replace($find, $replace, $output);
    
    // add sitemap
    if ($public && !preg_match('/sitemap_index\.xml/', $output)) {
      $output .= "\r\n\r\n".'Sitemap: '.get_site_url().'/sitemap_index.xml';
    }
    return $output;
  }

```
Maybe only the last part if you keep the sitemaps and only used when sitemaps are enabled. Just a suggestion though.

**Comment by senlin** [comment]
Just removed the htaccess editor, so that part of this issue has been completed.

@robneu @Hube2 Shall I go ahead and remove the robots.txt editor too then? Or do we add an adapted robots.txt file as per @Hube2 suggestions?

Regarding the sitemap I would like to see whether there is a volunteer who wants to add that and commit to keep it going for at least a year or two. If there is not such a person, then I suggest to drop the whole thing.

**Comment by robneu** [comment]
I think removing them both is the best plan for now. 

As far as filtering the virtual robots.txt output... you should probably submit a core patch for the admin-ajax issue and the sitemap would only make sense if we include the sitemap as part of the core plugin so we can probably skip that for the time being.

**Comment by PointandStare** [comment]
I think you need to set 2 rules right from the outset:
1, Who is the plugin aimed at (devs or clients)
2, What is the purpose of the plugin

I would say:
1, Clients - to allow them to automatically/ manually adjust SEO options within pages/ posts.
2, To provide SEO targeted facilities within a WordPress environment

Might have these slightly wrong, these are just my thoughts, but I think nailing these 2 down will help steer the direction.
