### ISSUE TITLE
Huge seo issue notice, remove or keep?

### ISSUE THREAD

**Issue by senlin** [senlin/ymbeseo#27]
When the box to discourage search engines from indexing the site has been ticked, the plugin shows a ridiculous warning message.

<img width="1128" alt="huge-seo-issue" src="https://cloud.githubusercontent.com/assets/650066/11769742/220ad1b8-a229-11e5-8c57-bfd66607ba5b.png">

I'm of the opinion that most people that tick that box know what they're doing and therefore this warnings not needed. 

If there are people that *forget* they have this setting, then we could perhaps show a warning, but hopefully less outrageous as this one?

Your input please, I'm for complete removal.

**Comment by robneu** [comment]
I'd probably keep this one. It's pretty easy to mistakenly set a site to noindex without realizing it, particularly when moving from dev->staging->production etc.

**Comment by senlin** [comment]
True, but does it need to show on all pages and in this fashion you think?

If we're keeping it, then I definitely want to change the wording...
