### ISSUE TITLE
Will we use the i18n module?

### ISSUE THREAD

**Issue by senlin** [senlin/ymbeseo#29]
Now that all plugins are being translated via WordPress, is it necessary to add it to GlotPress too like the original plugin does?

See https://github.com/senlin/ymbeseo/blob/development/admin/class-admin-init.php#L206-L224

**Comment by senlin** [comment]
uses the hook `ymbeseo_admin_footer` and shows only on sites where language is not English

**Comment by robneu** [comment]
The code linked there is just an advertisement to try to get more people to help out with translations. Unless you plan on maintaining a GlotPress installation for this plugin, we probably don't need that or the 3rd party composer library.

**Comment by senlin** [comment]
ok thanks, will remove the lot then
