### ISSUE TITLE
Anyone an idea what ymbeseo_admin_footer does?

### ISSUE THREAD

**Issue by senlin** [senlin/ymbeseo#32]
`ymbeseo_admin_footer` is referenced on many different pages, but I cannot put my finger on what it does?

Anyone knows? Can we remove it?

**Comment by PointandStare** [comment]
I use _admin_footer in my CMS plugin - essentially it adds/ changes content in the admin footer (ya don't say!).

I would advise removing any _admin_footer calls from this plugin as any content in admin has zero SEO effect.

**Comment by robneu** [comment]
The only remaining reference I can find to `ymbeseo_admin_footer` is an action hook within the Yoast form class: `do_action( 'ymbeseo_admin_footer' );`

It used to be where the class that was removed in #29 output, but now I don't think it's doing anything by default. It could be useful for add-on plugins perhaps?

**Comment by senlin** [comment]
@robneu Yes, you are right, the glotpress advertisement was added to the `ymbeseo_admin_footer `. I didn't realise that it doesn't seem to serve any other function.

> It could be useful for add-on plugins perhaps?

I don't know. Can it? If someone wants to do the sitemap functionality as an addon, is this function then useful? Since you're using the plural, were/are you thinking of any other addons?

**Comment by senlin** [comment]
As I have not heard anything back on the sitemap functionality, I am ditching it and therefore we can also ditch this `ymbeseo_admin_footer`.
