### ISSUE TITLE
proposal to un-check stopwords box by default

### ISSUE THREAD

**Issue by senlin** [senlin/ymbeseo#33]
The Yoast plugin has the stopwords box checked by default (Advanced > Permalinks).

With an eye on *options, not decisions* I would like to un-check this box by default and leave it up to the user to make the decision.

Feedback please.

**Comment by robneu** [comment]
I'd actually prefer to make more default choices for users rather than less. There are a number of things in WP SEO that probably should be defaults on 90% of sites but aren't for whatever reason. I suspect to increase Joost's pockets via consulting and audit sales.

**Comment by senlin** [comment]
@robneu Curious to see a list of things that you would like to see as default :)

Always good to hear what others think. Perhaps I'm with a minority always turning this off :)

**Comment by chuckreynolds** [comment]
:+1:

**Comment by senlin** [comment]
due to lack of further input I have moved forward and ticked the box off by default. If people want this option, they can turn it on in the plugin's settings.
