### ISSUE TITLE
Remove Admin Notices

### ISSUE THREAD

**Issue by CharlieLivingston** [senlin/ymbeseo#4]
One issue I have with 2.3.5 is the admin notices never go away, the ones that say 'Don't miss your crawl errors: connect with Google Search Console here.' and 'Yoast SEO has been updated to version 2.3.5. Click here to find out what's new!'

This is despite dismissing them hundreds (maybe thousands) of times. Would be great to get this fixed.

**Comment by Hube2** [comment]
As far as I'm concerned all of those admin notices are going. The only useful one is the one reminding me that I have search engines blocked so that I remember to unblock them when I make a site live.

**Comment by daltonrooney** [comment]
👍
Really appreciate this fork, thanks for putting this together.

**Comment by robneu** [comment]
+1 to removing most if not all of the notices this plugin creates. Personally, I'd like to rip out the entire search console functionality.

**Comment by senlin** [comment]
My SO Clean Up Yoast SEO plugin already does away with all those notices. The fork will definitely not irritate users.

For the rest, thanks for all your input and sorry to reply so late. 

I'm on holiday with hardly any internet access. I will get back to all of this after Dec 14th. 

Cheers,
Piet

**Comment by senlin** [comment]
reverted removal of "Reminder: Access to robots is currently being blocked." as we already changed the wording of this with issue #27 (previously it was called Huge SEO issue and had a red danger color, in issue 27 we changed it into an orange warning color and changed the wording too).
