### ISSUE TITLE
Create Roadmap?

### ISSUE THREAD

**Issue by robneu** [senlin/ymbeseo#5]
I'd love to get involved with this project. If you can line item the features you want to remove and issues that need to be addressed I'll start knocking out as many as I can whenever I have a spare minute.

**Comment by daltonrooney** [comment]
Is it safe to assume that most of the changes from this plugin will be merged in? https://github.com/senlin/so-clean-up-wp-seo

**Comment by senlin** [comment]
Hi guys, thanks for all your input and sorry to reply so late. 

I'm on holiday with hardly any internet access. I will get back to all of this after Dec 14th. 

Cheers,
Piet

**Comment by senlin** [comment]
@daltonrooney my clean up plugin your refer to mostly does the display:none thing. The fork needs to do a lot more than just display none; it needs to eradicate the fluff :)

**Comment by senlin** [comment]
@robneu good suggestion about a roadmap! How do you suggest to add such a roadmap? Should I open an issue for that or add it to the readme file or sth else perhaps?

**Comment by robneu** [comment]
@senlin Since we're working here on GitHub we can probably just use the roadmap feature and make each change an issue with a proposed version for when we'd like to get it added/removed.

If you'd be willing to give me commit access I can help out with organizing and labeling everything or if you're not comfortable I can just start opening issues and you can organize them as you see fit.

**Comment by senlin** [comment]
@robneu great thank you, I have made you a collaborator and hope that means you now also have commit access.

**Comment by robneu** [comment]
Yup, looks like it. Thanks! I went ahead and created a development branch and set up a `1.0.0` milestone. Closing this out. :+1:
